##############################################################################
## Configuration file for TekkitRestrict                                    ##
## Authors: Taeir, DreadEnd (aka DreadSlicer)                               ##
## BukkitDev: http://dev.bukkit.org/server-mods/tekkit-restrict/            ##
## Please ask questions/report issues on the BukkitDev page.                ##
##############################################################################

##############################################################################
############################# EEPatch Functions ##############################
##############################################################################