#Configuration file for TekkitRestrict
#Author: DreadEnd
#Email: dreadslicer@gmail.com
#BukkitDev: http://dev.bukkit.org/server-mods/tekkit-restrict/

#################################################
######### Anti-Hack Configuration ######### 
# Block hackers from screwing your server up!

## Move Speed Max is the speed in Blocks/second
## (~3 seconds) Move Speed Tolerance is based off the number of "Moves" a player does.

## Fly hack Tolerance is based off the number of "Moves" a player does (1~5 per second).

## Forcefield Tolerance is based off the number of times a player hits a mob or player.

####Default hack names
##	"fly", "forcefield", "speed"

###########################################################################################
# Enabled:      Do you want to enable Anti-Hack for this kind of hack?
# Tolerance:    The amount of ticks the player has to hack before he is kicked.
#               If you set this too low, innocent people might get kicked for connection
#               problems.
# MaxMoveSpeed: The maximum speed a player can have (in blocks per second).
#               Speeds above this are considered hacking.
#               People with quantum armor will have 3 times this limit.
# MinHeight:    Minimal Height for the flycheck to kick in.
#               If you set this too low, people might get kicked for jumping.
# Angle:        The maximal angle you are allowed to hit a player with.
Anti-Hacks:
    MoveSpeed:
        Enabled: true
        Tolerance: 30
        MaxMoveSpeed: 2.5
    Fly:
        Enabled: true
        Tolerance: 60
        MinHeight: 3
    Forcefield:
        Enabled: true
        Tolerance: 30
        Angle: 40


HackBan: []
HackKick: ["fly","forcefield","speed"]
HackBroadcasts: ["fly","forcefield","speed"]
HackBroadcastString: "{PLAYER} tried to {TYPE}-hack!"


####Dupes####
Anti-Dupes:
    PreventAlchemyBagDupe: true
    PreventRMFurnaceDupe: true
    PreventTransmuteDupe: true
    PreventTankCartDupe: true
    PreventTankCartGlitch: true
    PreventTeleportDupe: true
    PreventPedestalEmcGen: true
    BroadcastString: "{PLAYER} tried to dupe using {TYPE}!"
    Broadcast: ["rmfurnace", "alc"]
    Kick: []
#####        "RMFurnace", "alc", "transmute", "tankcart"







##############################
##############################
##############################
