##########################################################################################
## Configuration file for TekkitRestrict                                                ##
## Authors: Taeir, DreadEnd (aka DreadSlicer)                                           ##
## BukkitDev: http://dev.bukkit.org/server-mods/tekkit-restrict/                        ##
## Please ask questions/report issues on the BukkitDev page.                            ##
##########################################################################################

##########################################################################################
################################ Anti-Hack Configuration #################################
##########################################################################################
# Block hackers from screwing your server up!
#
# Enabled:      Do you want to enable Anti-Hack for this kind of hack?
# Tolerance:    The amount of ticks the player has to hack before he is kicked.
#               If you set this too low, innocent people might get kicked for connection
#               problems.
# MaxMoveSpeed: The maximum speed a player can have (in blocks per second).
#               Speeds above this are considered hacking.
#               People with quantum armor will have 3 times this limit.
# MinHeight:    Minimal Height for the flycheck to kick in.
#               If you set this too low, people might get kicked for jumping.
# Angle:        The maximal angle you are allowed to hit a player with.
Anti-Hacks:
    MoveSpeed:
        Enabled: true
        Tolerance: 30
        MaxMoveSpeed: 2.5
    Fly:
        Enabled: true
        Tolerance: 60
        MinHeight: 3
    Forcefield:
        Enabled: true
        Tolerance: 30
        Angle: 40

# A player will be kicked if he hacks with any of the types listed here.
#
# Possible: fly", "forcefield" and "speed"
# Default: ["fly","forcefield","speed"]
HackKick: ["fly","forcefield","speed"]

# If someone hacks and the hacktype is in this list, it is broadcasted to players on the
# server with the tekkitrestrict.notify.hack permission.
#
# Possible: fly", "forcefield" and "speed"
# Default: ["fly","forcefield","speed"]
HackBroadcasts: ["fly","forcefield","speed"]

# The formatting of the BroadcastString.
#
# Default: "{PLAYER} tried to {TYPE}-hack!"
HackBroadcastString: "{PLAYER} tried to {TYPE}-hack!"

##########################################################################################
################################ Anti-Dupe Configuration #################################
##########################################################################################
# BroadcastString: The formatting of the BroadcastString for dupes.
# Default: "{PLAYER} tried to dupe using {TYPE}!"
#
# Broadcast: If someone tries to dupe and the dupetype is in this list, it is broadcasted
#            to players on the server with the tekkitrestrict.notify.dupe permission.
# Possible: "rmfurnace", "alc", "transmute", "tankcart"
# Default: ["rmfurnace", "alc", "tankcart"]
#
# Kick: If a player dupes with a dupetype listed here, he will be kicked.
#       NOTE: It is not recommended to kick players on attempting to dupe. In most cases
#             it was not the players intention to dupe.
# Possible: "rmfurnace", "alc", "transmute", "tankcart"
# Default: []
Anti-Dupes:
    PreventAlchemyBagDupe: true
    PreventRMFurnaceDupe: true
    PreventTransmuteDupe: true
    PreventTankCartDupe: true
    PreventTankCartGlitch: true
    PreventTeleportDupe: true
    PreventPedestalEmcGen: true
    BroadcastString: "{PLAYER} tried to dupe using {TYPE}!"
    Broadcast: ["rmfurnace", "alc", "tankcart"]
    Kick: []

##########################################################################################