######################################################################
## Configuration file for TekkitRestrict                            ##
## Authors: Taeir, DreadEnd (aka DreadSlicer)                       ##
## BukkitDev: http://dev.bukkit.org/server-mods/tekkit-restrict/    ##
## Please ask questions/report issues on the BukkitDev page.        ##
######################################################################

######################################################################
#################### LimitedCreative Configuration ###################
######################################################################

# If this is enabled, it prevents the use of ANY container while in
# creative mode. This is everything you can interact with with the
# exception of your own inventory.
# Default: true
LimitedCreativeNoContainer: true

# Prevent the use of these mods or IDs in creative
LimitedCreative:
- EE
- RedPowerControl
- RedPowerLogic
- RedPowerMachine
- WirelessRedstone
- BuildCraft
- AdditionalPipes
- AdvancedMachines
- IndustrialCraft
- NuclearControl
- CompactSolars
- ChargingBench
- PowerConverters
- Mffs
- RailCraft
- TubeStuffs
- IronChests
- BalkonWeaponMod
- EnderChest
- ChunkLoaders
#- RedPowerCore
#- RedPowerLighting

######################################################################