#####################################################################################
## Configuration file for TekkitRestrict                                           ##
## Authors: Taeir, DreadEnd (aka DreadSlicer)                                      ##
## BukkitDev: http://dev.bukkit.org/server-mods/tekkit-restrict/                   ##
## Please ask questions/report issues on the BukkitDev page.                       ##
#####################################################################################

#####################################################################################
########################## Micro Permissions Configuration ##########################
#####################################################################################

# You can find more information on:
# http://dev.bukkit.org/server-mods/tekkit-restrict/pages/config-micro-permisisons/

# Permission: tekkitrestrict.noitem.[name]
#             tekkitrestrict.limiter.[name]
#             tekkitrestrict.creative.[name]

MicroPermissions:
    NoItem:
        default: ""
    BlockLimiter:
        default: ""
    LimitedCreative:
        default: ""


#####################################################################################
