##########################################################################################
## Configuration file for TekkitRestrict                                                ##
## Authors: Taeir, DreadEnd (aka DreadSlicer)                                           ##
## BukkitDev: http://dev.bukkit.org/server-mods/tekkit-restrict/                        ##
## Please ask questions/report issues on the BukkitDev page.                            ##
##########################################################################################

##########################################################################################
################################ Mod Modifications Config ################################
##########################################################################################

# Limit fly time using rings and jet packs in minutes
# NOTE: This feature is currently not working.
# Default: false
LimitFlightTime: false
FlyLimitDailyMinutes: 9999999

# Should offensive powers of gemarmor be allowed? (explosion, lightning)
# Default: false
AllowGemArmorOffensive: false

# Should the defensive powers of gemarmor be allowed? (flying, automatic running)
# Default: true
AllowGemArmorDefensive: true

# Set RedPower timers minimum time in seconds
# Default: 1.0
RPTimerMin: 1.0

##########################################################################################
######################################### Set EMC ########################################
##########################################################################################

# Set or change EMC Values for ANY item, block or tool, even the ones that usually don't
# have EMC values.
#
# Example: HARD Mode -> DarkMatter, DM Blocks, RedMatter, RMBlocks EMC*2.
#- "27541 300000"
#- "126:8 800000"
#- "27563 900000"
#- "126:9 1300000"
#
# DEFAULT: EMC farm removal [Milk, Blaze Rod, Bonemeal, Indigo Flower, Flower, Rose, Seed]
SetEMC: 
- "335 100"
- "369 780"
- "351:15 30"
- "139 4"
- "37 4"
- "38 4"
- "295 4"

##########################################################################################
####################################### Item Max EU ######################################
##########################################################################################

# Set the Max EU storable in an IC2 Item (Check out IC2 Wiki for MaxEU details)
#
# Some default EU values:
#- "30148 40000" #Nano saber
#- "30234 10000" #Diamond Drill
#- "30177 100000" #ANY piece Nano Armor
#- "30173 1000000" #ANY piece Quantum Armor
#
# Examples:
# Charge Quantum armor set 2x slower
#- "30171-30174 1000000 500"
# Charge Quantum armor set 4x slower
#- "30171-30174 1000000 250"
MaxEU: []

##########################################################################################
################################### Max EE Tool Charge ###################################
##########################################################################################
# MaxCharge limits the maximum EE charge of an item. (0-100%)
#- "27573 30" (This will set the max charge of a morning star to 30%)
#- "27564-27573 50" (This will Gimp ALL Red Matter Tools down to only 50% charge capacity)
MaxCharge: []

# This will automatically decharge set EE items when a player enters a safezone.
# NOTE: Requires DechargeEE in SafeZones.config to be true
DechargeInSS: 
- 27526
- 27527
- 27530
- 27531
- 27533
- 27534
- 27535
- 27583
- 27593
- 27543
- 27544
- 27545
- 27546
- 27547
- 27548
- 27564
- 27565
- 27566
- 27567
- 27568
- 27569
- 27570
- 27572
- 27573
- 27574

##########################################################################################